#!/bin/bash
#sbatch --job-name=case57 --partition=scaling --output=case57.out ./run_tests line_real_power 18.0 0.2

filename='case3_lmbd'

mkdir output_files

for f in $filename
   do
      sbatch --job-name=$f --partition=scaling --output=output_files/$f.out ./run_tests $f
   done
