#!/bin/bash


filename='case1951_rte'

mkdir output_files_AC_case1951
mkdir results_ACnormal_case1951

for f in $filename
   do
      sbatch --job-name=$f --qos=scavenge --time=7-00:00:00 --partition=scaling --output=output_files_AC_case1951/$f.out ./run_tests_AC_case300 $f
   done
